// ========================================
// 215+ MALAYSIA ZERO-TIER DOMAINS
// ========================================
const DOMAINS = [
  // === SPEEDTEST & CDN (10) ===
  { name: "Speedtest KL", host: "ookla.kul1.speedtest.net", cf: true, zt: true },
  { name: "Speedtest MY", host: "www.speedtest.net", cf: true, zt: true },
  { name: "Fast.com", host: "fast.com", cf: false, zt: true },
  { name: "Cloudflare MY", host: "1.1.1.1", cf: true, zt: true },
  { name: "Cloudflare DNS", host: "cloudflare-dns.com", cf: true, zt: true },
  { name: "Akamai MY", host: "a248.e.akamai.net", cf: false, zt: true },
  { name: "Google DNS", host: "dns.google", cf: true, zt: true },
  { name: "Speedtest Global", host: "speedtest.net", cf: true, zt: true },
  { name: "Ookla Server", host: "www.ookla.com", cf: false, zt: true },
  { name: "CF KL Edge", host: "kuala-lumpur.cloudflare.com", cf: true, zt: true },

  // === GOOGLE & YOUTUBE (15) ===
  { name: "YouTube MY", host: "www.youtube.com", cf: true, zt: true },
  { name: "Google MY", host: "www.google.com.my", cf: true, zt: true },
  { name: "Google Search", host: "www.google.com", cf: true, zt: true },
  { name: "YouTube CDN", host: "googlevideo.com", cf: true, zt: true },
  { name: "Google Drive", host: "drive.google.com", cf: true, zt: true },
  { name: "Google Maps MY", host: "maps.google.com.my", cf: true, zt: true },
  { name: "YouTube Player", host: "youtube.com", cf: true, zt: true },
  { name: "Google Classroom", host: "classroom.google.com", cf: true, zt: true },
  { name: "YouTube Kids", host: "www.youtubekids.com", cf: true, zt: true },
  { name: "Google Scholar", host: "scholar.google.com.my", cf: true, zt: true },
  { name: "YouTube Music", host: "music.youtube.com", cf: true, zt: true },
  { name: "Google Translate", host: "translate.google.com", cf: true, zt: true },
  { name: "YouTube Premium", host: "www.youtube.com", cf: true, zt: true },
  { name: "Google Books", host: "books.google.com.my", cf: true, zt: true },
  { name: "YouTube Studio", host: "studio.youtube.com", cf: true, zt: true },

  // === SOCIAL & MESSAGING (20) ===
  { name: "Facebook MY", host: "edge.facebook.com", cf: true, zt: true },
  { name: "Instagram MY", host: "i.instagram.com", cf: true, zt: true },
  { name: "WhatsApp MY", host: "mmg.whatsapp.net", cf: false, zt: true },
  { name: "Telegram MY", host: "web.telegram.org", cf: true, zt: true },
  { name: "Facebook Messenger", host: "www.messenger.com", cf: true, zt: true },
  { name: "Instagram Feed", host: "www.instagram.com", cf: true, zt: true },
  { name: "WhatsApp Web", host: "web.whatsapp.com", cf: false, zt: true },
  { name: "Telegram Desktop", host: "desktop.telegram.org", cf: true, zt: true },
  { name: "Facebook Lite", host: "lite.facebook.com", cf: true, zt: true },
  { name: "Instagram Stories", host: "www.instagram.com", cf: true, zt: true },
  { name: "WhatsApp Business", host: "business.whatsapp.com", cf: false, zt: true },
  { name: "Telegram Channels", host: "t.me", cf: true, zt: true },
  { name: "Facebook Groups", host: "www.facebook.com", cf: true, zt: true },
  { name: "Instagram Reels", host: "www.instagram.com", cf: true, zt: true },
  { name: "WhatsApp API", host: "api.whatsapp.com", cf: false, zt: true },
  { name: "Telegram Bots", host: "core.telegram.org", cf: true, zt: true },
  { name: "Facebook Marketplace", host: "www.facebook.com", cf: true, zt: true },
  { name: "Instagram Explore", host: "www.instagram.com", cf: true, zt: true },
  { name: "WhatsApp Status", host: "www.whatsapp.com", cf: false, zt: true },
  { name: "Telegram Voice", host: "telegram.org", cf: true, zt: true },

  // === E-COMMERCE & SERVICES (25) ===
  { name: "Shopee MY", host: "shopee.com.my", cf: true, zt: true },
  { name: "Lazada MY", host: "my.lazada.com", cf: true, zt: true },
  { name: "Grab MY", host: "m.grab.com", cf: true, zt: true },
  { name: "Shopee Mall", host: "mall.shopee.com.my", cf: true, zt: true },
  { name: "Lazada Category", host: "www.lazada.com.my", cf: true, zt: true },
  { name: "Grab Food", host: "food.grab.com", cf: true, zt: true },
  { name: "Shopee Live", host: "shopee.com.my", cf: true, zt: true },
  { name: "Lazada Deals", host: "my.lazada.com", cf: true, zt: true },
  { name: "Grab Mart", host: "mart.grab.com", cf: true, zt: true },
  { name: "Shopee Games", host: "shopee.com.my", cf: true, zt: true },
  { name: "Lazada Wallet", host: "www.lazada.com.my", cf: true, zt: true },
  { name: "Grab Pay", host: "pay.grab.com", cf: true, zt: true },
  { name: "Shopee Coins", host: "shopee.com.my", cf: true, zt: true },
  { name: "Lazada Club", host: "my.lazada.com", cf: true, zt: true },
  { name: "Grab Rides", host: "www.grab.com", cf: true, zt: true },
  { name: "Shopee Affiliate", host: "affiliate.shopee.com.my", cf: true, zt: true },
  { name: "Lazada Global", host: "www.lazada.com.my", cf: true, zt: true },
  { name: "Grab Services", host: "services.grab.com", cf: true, zt: true },
  { name: "Shopee Support", host: "help.shopee.com.my", cf: true, zt: true },
  { name: "Lazada Help", host: "help.lazada.com.my", cf: true, zt: true },
  { name: "Grab Help", host: "help.grab.com", cf: true, zt: true },
  { name: "Shopee Flash", host: "shopee.com.my", cf: true, zt: true },
  { name: "Lazada Flash", host: "my.lazada.com", cf: true, zt: true },
  { name: "Grab Express", host: "express.grab.com", cf: true, zt: true },
  { name: "Shopee Vouchers", host: "shopee.com.my", cf: true, zt: true },

  // === BANKING & FINANCE (20) ===
  { name: "Maybank2u", host: "www.maybank2u.com.my", cf: true, zt: true },
  { name: "CIMB Clicks", host: "www.cimbclicks.com.my", cf: true, zt: true },
  { name: "Public Bank", host: "www.pbebank.com", cf: true, zt: true },
  { name: "RHB Now", host: "www.rhbgroup.com", cf: true, zt: true },
  { name: "Hong Leong Connect", host: "www.hlb.com.my", cf: true, zt: true },
  { name: "Maybank MAE", host: "maeapp.maybank2u.com.my", cf: true, zt: true },
  { name: "CIMB Preferred", host: "www.cimb.com", cf: true, zt: true },
  { name: "Public e-Banking", host: "www.publicbankgroup.com", cf: true, zt: true },
  { name: "RHB Online", host: "rhbnow.rhbgroup.com", cf: true, zt: true },
  { name: "HLB ConnectFirst", host: "www.hlb.com.my", cf: true, zt: true },
  { name: "Maybank Islamic", host: "www.maybank-islamic.com.my", cf: true, zt: true },
  { name: "CIMB Islamic", host: "www.cimbislamic.com.my", cf: true, zt: true },
  { name: "Public Islamic", host: "www.publicislamicbank.com.my", cf: true, zt: true },
  { name: "RHB Islamic", host: "www.rhbgroup.com", cf: true, zt: true },
  { name: "HLB Islamic", host: "www.hlb.com.my", cf: true, zt: true },
  { name: "Maybank Investment", host: "www.maybank.com", cf: true, zt: true },
  { name: "CIMB Investment", host: "www.cimb.com", cf: true, zt: true },
  { name: "Public Wealth", host: "www.publicbank.com.my", cf: true, zt: true },
  { name: "RHB Wealth", host: "www.rhbgroup.com", cf: true, zt: true },
  { name: "HLB Wealth", host: "www.hlb.com.my", cf: true, zt: true },

  // === GOVERNMENT & EDUCATION (30) ===
  { name: "MyGov", host: "www.malaysia.gov.my", cf: false, zt: true },
  { name: "MCMC", host: "www.mcmc.gov.my", cf: false, zt: true },
  { name: "MDEC", host: "mdec.my", cf: false, zt: true },
  { name: "MySejahtera", host: "mysejahtera.moh.gov.my", cf: false, zt: true },
  { name: "MyTrace", host: "mytrace.moh.gov.my", cf: false, zt: true },
  { name: "Gerak Malaysia", host: "gerak.malaysia.gov.my", cf: false, zt: true },
  { name: "JPN", host: "www.jpn.gov.my", cf: false, zt: true },
  { name: "Jabatan Kerja Raya", host: "www.jkr.gov.my", cf: false, zt: true },
  { name: "Kementerian Kesihatan", host: "www.moh.gov.my", cf: false, zt: true },
  { name: "Kementerian Pendidikan", host: "www.moe.gov.my", cf: false, zt: true },
  { name: "UKM", host: "www.ukm.my", cf: true, zt: true },
  { name: "UM", host: "www.um.edu.my", cf: true, zt: true },
  { name: "UPM", host: "www.upm.edu.my", cf: true, zt: true },
  { name: "UTM", host: "www.utm.my", cf: true, zt: true },
  { name: "USM", host: "www.usm.my", cf: true, zt: true },
  { name: "UMS", host: "www.ums.edu.my", cf: true, zt: true },
  { name: "UniMAP", host: "www.unimap.edu.my", cf: true, zt: true },
  { name: "UniSZA", host: "www.unisza.edu.my", cf: true, zt: true },
  { name: "UCSI", host: "www.ucsiuniversity.edu.my", cf: true, zt: true },
  { name: "Taylor's Uni", host: "university.taylors.edu.my", cf: true, zt: true },
  { name: "Sunway Uni", host: "university.sunway.edu.my", cf: true, zt: true },
  { name: "Monash MY", host: "www.monash.edu.my", cf: true, zt: true },
  { name: "Nottingham MY", host: "www.nottingham.edu.my", cf: true, zt: true },
  { name: "Heriot-Watt MY", host: "www.hw.ac.uk/my", cf: true, zt: true },
  { name: "Newcastle MY", host: "www.newcastle.edu.my", cf: true, zt: true },
  { name: "Curtin MY", host: "curtin.edu.my", cf: true, zt: true },
  { name: "Swinburne MY", host: "www.swinburne.edu.my", cf: true, zt: true },
  { name: "MMU", host: "www.mmu.edu.my", cf: true, zt: true },
  { name: "UTAR", host: "www.utar.edu.my", cf: true, zt: true },
  { name: "INTI", host: "newinti.edu.my", cf: true, zt: true },

  // === NEWS & MEDIA (15) ===
  { name: "Astro Awani", host: "www.astroawani.com", cf: true, zt: true },
  { name: "The Star", host: "www.thestar.com.my", cf: true, zt: true },
  { name: "Berita Harian", host: "www.bharian.com.my", cf: true, zt: true },
  { name: "Utusan MY", host: "www.utusan.com.my", cf: true, zt: true },
  { name: "Sin Chew Daily", host: "www.sinchew.com.my", cf: true, zt: true },
  { name: "Malay Mail", host: "www.malaymail.com", cf: true, zt: true },
  { name: "Free Malaysia Today", host: "www.freemalaysiatoday.com", cf: true, zt: true },
  { name: "Malaysiakini", host: "www.malaysiakini.com", cf: true, zt: true },
  { name: "NST", host: "www.nst.com.my", cf: true, zt: true },
  { name: "The Edge MY", host: "theedgemalaysia.com", cf: true, zt: true },
  { name: "Sinar Harian", host: "www.sinarharian.com.my", cf: true, zt: true },
  { name: "Kosmo", host: "www.kosmo.com.my", cf: true, zt: true },
  { name: "Harian Metro", host: "www.hmetro.com.my", cf: true, zt: true },
  { name: "The Rakyat Post", host: "www.therakyatpost.com", cf: true, zt: true },
  { name: "Malay Mail Online", host: "www.malaymail.com", cf: true, zt: true },

  // === TELCOS & ISP (10) ===
  { name: "Unifi", host: "unifi.com.my", cf: true, zt: true },
  { name: "TM Net", host: "www.tm.com.my", cf: false, zt: true },
  { name: "Maxis", host: "www.maxis.com.my", cf: true, zt: true },
  { name: "Celcom", host: "www.celcom.com.my", cf: true, zt: true },
  { name: "Digi", host: "www.digi.com.my", cf: true, zt: true },
  { name: "Hotlink", host: "www.hotlink.com.my", cf: true, zt: true },
  { name: "U Mobile", host: "www.u.com.my", cf: true, zt: true },
  { name: "Yes 5G", host: "www.yes.my", cf: true, zt: true },
  { name: "TIME Internet", host: "www.time.com.my", cf: true, zt: true },
  { name: "RedOne", host: "www.redonemobile.com.my", cf: true, zt: true },

  // === HEALTH & COVID (10) ===
  { name: "MySejahtera App", host: "mysejahtera.moh.gov.my", cf: false, zt: true },
  { name: "MyTrace App", host: "mytrace.moh.gov.my", cf: false, zt: true },
  { name: "Gerak App", host: "gerak.malaysia.gov.my", cf: false, zt: true },
  { name: "MOH Portal", host: "covid-19.moh.gov.my", cf: false, zt: true },
  { name: "KKM Vaccine", host: "vaccine.moh.gov.my", cf: false, zt: true },
  { name: "Health Info", host: "www.myhealth.gov.my", cf: false, zt: true },
  { name: "COVID Dashboard", host: "covid19dashboard.moh.gov.my", cf: false, zt: true },
  { name: "PJKNI Portal", host: "www.pjkni.gov.my", cf: false, zt: true },
  { name: "Quarantine App", host: "gk.moh.gov.my", cf: false, zt: true },
  { name: "Health Guidelines", host: "www.moh.gov.my", cf: false, zt: true },

  // === EDUCATION PLATFORMS (20) ===
  { name: "Udemy MY", host: "www.udemy.com", cf: true, zt: true },
  { name: "Coursera", host: "www.coursera.org", cf: true, zt: true },
  { name: "edX", host: "www.edx.org", cf: true, zt: true },
  { name: "Khan Academy", host: "www.khanacademy.org", cf: true, zt: true },
  { name: "Zoom Education", host: "zoom.us", cf: true, zt: true },
  { name: "Microsoft Teams", host: "teams.microsoft.com", cf: true, zt: true },
  { name: "Google Classroom MY", host: "classroom.google.com", cf: true, zt: true },
  { name: "Moodle MY", host: "moodle.org", cf: true, zt: true },
  { name: "SunagoLearn", host: "sunagolearn.com", cf: false, zt: true },
  { name: "Classruum", host: "classruum.com", cf: false, zt: true },
  { name: "Teach for MY", host: "teachformalaysia.org", cf: true, zt: true },
  { name: "Open University MY", host: "www.oum.edu.my", cf: true, zt: true },
  { name: "SEGi Uni", host: "www.segi.edu.my", cf: true, zt: true },
  { name: "HELP Uni", host: "university.help.edu.my", cf: true, zt: true },
  { name: "Binary Uni", host: "www.bu.edu.my", cf: true, zt: true },
  { name: "Limkokwing", host: "www.limkokwing.net", cf: true, zt: true },
  { name: "Perdana Uni", host: "www.upm.edu.my", cf: true, zt: true },
  { name: "Xiamen Uni MY", host: "www.xmu.edu.my", cf: true, zt: true },
  { name: "Asia Pacific Uni", host: "www.apu.edu.my", cf: true, zt: true },
  { name: "Management Tech", host: "www.mgt.edu.my", cf: true, zt: true },

  // === ENTERTAINMENT & STREAMING (15) ===
  { name: "Netflix MY", host: "www.netflix.com", cf: true, zt: true },
  { name: "Disney+ Hotstar", host: "www.hotstar.com/my", cf: true, zt: true },
  { name: "HBO Max MY", host: "www.hbomax.com", cf: true, zt: true },
  { name: "Viu MY", host: "www.viu.com", cf: true, zt: true },
  { name: "TVB Jade", host: "www.tvb.com", cf: true, zt: true },
  { name: "SPOTV MY", host: "www.spotv.asia", cf: true, zt: true },
  { name: "beIN SPORTS", host: "bein.com", cf: true, zt: true },
  { name: "Astro GO", host: "www.astro.com.my", cf: true, zt: true },
  { name: "Unifi TV", host: "tv.unifi.com.my", cf: true, zt: true },
  { name: "Spotify MY", host: "open.spotify.com", cf: true, zt: true },
  { name: "Twitch MY", host: "www.twitch.tv", cf: true, zt: true },
  { name: "TikTok MY", host: "www.tiktok.com", cf: true, zt: true },
  { name: "Reddit MY", host: "www.reddit.com", cf: true, zt: true },
  { name: "Discord MY", host: "discord.com", cf: true, zt: true },
  { name: "Steam MY", host: "store.steampowered.com", cf: true, zt: true },

  // === MISC & ADDITIONAL (55+) ===
  { name: "GitHub", host: "github.com", cf: true, zt: true },
  { name: "Wikipedia MY", host: "en.wikipedia.org", cf: true, zt: true },
  { name: "BBC News", host: "www.bbc.com", cf: true, zt: true },
  { name: "CNN", host: "edition.cnn.com", cf: true, zt: true },
  { name: "Al Jazeera", host: "www.aljazeera.com", cf: true, zt: true },
  { name: "Reuters", host: "www.reuters.com", cf: true, zt: true },
  { name: "Bloomberg", host: "www.bloomberg.com", cf: true, zt: true },
  { name: "Forbes", host: "www.forbes.com", cf: true, zt: true },
  { name: "LinkedIn MY", host: "www.linkedin.com", cf: true, zt: true },
  { name: "Twitter MY", host: "twitter.com", cf: true, zt: true },
  { name: "Pinterest", host: "www.pinterest.com", cf: true, zt: true },
  { name: "Tumblr", host: "www.tumblr.com", cf: true, zt: true },
  { name: "Medium", host: "medium.com", cf: true, zt: true },
  { name: "Quora", host: "www.quora.com", cf: true, zt: true },
  { name: "Stack Overflow", host: "stackoverflow.com", cf: true, zt: true },
  { name: "Dropbox", host: "www.dropbox.com", cf: true, zt: true },
  { name: "OneDrive", host: "onedrive.live.com", cf: true, zt: true },
  { name: "iCloud", host: "www.icloud.com", cf: true, zt: true },
  { name: "Weather MY", host: "www.accuweather.com", cf: true, zt: true },
  { name: "TripAdvisor MY", host: "www.tripadvisor.com.my", cf: true, zt: true },
  { name: "Booking.com", host: "www.booking.com", cf: true, zt: true },
  { name: "Airbnb MY", host: "www.airbnb.com.my", cf: true, zt: true },
  { name: "Uber MY", host: "www.uber.com", cf: true, zt: true },
  { name: "Foodpanda MY", host: "www.foodpanda.com.my", cf: true, zt: true },
  { name: "Deliveroo MY", host: "deliveroo.com.my", cf: true, zt: true },
  { name: "Waze MY", host: "www.waze.com", cf: true, zt: true },
  { name: "MyFitnessPal", host: "www.myfitnesspal.com", cf: true, zt: true },
  { name: "Strava", host: "www.strava.com", cf: true, zt: true },
  { name: "Duolingo", host: "www.duolingo.com", cf: true, zt: true },
  { name: "Canva", host: "www.canva.com", cf: true, zt: true },
  { name: "Slack", host: "slack.com", cf: true, zt: true },
  { name: "Trello", host: "trello.com", cf: true, zt: true },
  { name: "Notion", host: "www.notion.so", cf: true, zt: true },
  { name: "Evernote", host: "evernote.com", cf: true, zt: true },
  { name: "PayPal MY", host: "www.paypal.com/my", cf: true, zt: true },
  { name: "Stripe", host: "stripe.com", cf: true, zt: true },
  { name: "Wise", host: "wise.com", cf: true, zt: true },
  { name: "Coinbase", host: "www.coinbase.com", cf: true, zt: true },
  { name: "Binance MY", host: "www.binance.com", cf: true, zt: true },
  { name: "Weather.com", host: "weather.com", cf: true, zt: true },
  { name: "IMDB", host: "www.imdb.com", cf: true, zt: true },
  { name: "Rotten Tomatoes", host: "www.rottentomatoes.com", cf: true, zt: true },
  { name: "Goodreads", host: "www.goodreads.com", cf: true, zt: true },
  { name: "SoundCloud", host: "soundcloud.com", cf: true, zt: true },
  { name: "Vimeo", host: "vimeo.com", cf: true, zt: true },
  { name: "Dailymotion", host: "www.dailymotion.com", cf: true, zt: true },
  { name: "Flickr", host: "www.flickr.com", cf: true, zt: true },
  { name: "500px", host: "500px.com", cf: true, zt: true },
  { name: "Behance", host: "www.behance.net", cf: true, zt: true },
  { name: "Dribbble", host: "dribbble.com", cf: true, zt: true },
  { name: "Unsplash", host: "unsplash.com", cf: true, zt: true },
  { name: "Pexels", host: "www.pexels.com", cf: true, zt: true },
  { name: "Pixabay", host: "pixabay.com", cf: true, zt: true },
  { name: "Freepik", host: "www.freepik.com", cf: true, zt: true },
  { name: "Envato", host: "elements.envato.com", cf: true, zt: true },
  { name: "Adobe Stock", host: "stock.adobe.com", cf: true, zt: true },
  { name: "Shutterstock", host: "www.shutterstock.com", cf: true, zt: true },
  { name: "Getty Images", host: "www.gettyimages.com", cf: true, zt: true },
  { name: "iStock", host: "www.istockphoto.com", cf: true, zt: true },
  { name: "Depositphotos", host: "depositphotos.com", cf: true, zt: true },
  { name: "Alamy", host: "www.alamy.com", cf: true, zt: true },
  { name: "123RF", host: "www.123rf.com", cf: true, zt: true }
  // Total: 215+
];

// ========================================
// 100+ PAYLOAD VARIANTS
// ========================================
const PAYLOADS = [
  // BASIC (20)
  { name: "CF Trace WS", payload: `GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "YouTube 204", payload: `GET /generate_204 HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Google Favicon", payload: `GET /favicon.ico HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "WhatsApp Direct", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Shopee API", payload: `GET /api/v4/homepage/recommend HTTP/1.1[crlf]Host: [DOMAIN][crlf]Accept: application/json[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Facebook Edge", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Instagram API", payload: `GET /api/v1/feed/timeline/ HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Telegram Web", payload: `GET /k/ HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Lazada Category", payload: `GET /category HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Grab Consumer", payload: `GET /consumer HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Maybank Login", payload: `GET /personal/login HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "CIMB Dashboard", payload: `GET /dashboard HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "MyGov Portal", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "UKM Home", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Astro Awani", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Unifi Portal", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Maxis Home", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "MySejahtera", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Zoom Meeting", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },

  // ADVANCED HEADERS (30)
  { name: "CF + Keep-Alive", payload: `GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [DOMAIN][crlf]Connection: Keep-Alive[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Range Bypass", payload: `GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [DOMAIN][crlf]Range: bytes=0-1024[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "X-Online-Host", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]X-Online-Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "CF-RAY Fake", payload: `GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [DOMAIN][crlf]CF-RAY: 8a1b2c3d4e5f[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Origin WS", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Origin: https://[DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "CF Visitor", payload: `GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [DOMAIN][crlf]CF-Visitor: {\"scheme\":\"https\"}[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Accept Gzip", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Accept-Encoding: gzip[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Referer Google", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Referer: https://www.google.com[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "X-Forwarded-For", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]X-Forwarded-For: 8.8.8.8[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Accept-Language EN", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Accept-Language: en-MY[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Cache-Control No", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Cache-Control: no-cache[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Pragma No-Cache", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Pragma: no-cache[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "DNT True", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]DNT: 1[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Sec-Fetch-Site None", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Sec-Fetch-Site: none[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Sec-Fetch-Mode No-CORS", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Sec-Fetch-Mode: no-cors[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Upgrade-Insecure", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Upgrade-Insecure-Requests: 1[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "FB Connection Close", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]X-FB-Connection: close[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "YT Range", payload: `GET /s/player/abc123/player_ias.js HTTP/1.1[crlf]Host: [DOMAIN][crlf]Range: bytes=0-1024[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "GG Referer", payload: `GET /search?q=bypass HTTP/1.1[crlf]Host: [DOMAIN][crlf]Referer: https://www.google.com[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "WA Origin", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Origin: https://web.whatsapp.com[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "CF Connecting-IP", payload: `GET /cdn-cgi/trace HTTP/1.1[crlf]Host: [DOMAIN][crlf]CF-Connecting-IP: 1.1.1.1[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Sec-WS-Key", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Sec-WebSocket-Key: dGhlIHNhbXBsZSBub25jZQ==[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Sec-WS-Version", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]Sec-WebSocket-Version: 13[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "X-WA-Device", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]X-WA-Device: Android[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "X-FB-Net", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf]X-FB-Net: true[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "X-YouTube", payload: `GET /s/player/abc123/player_ias.js HTTP/1.1[crlf]Host: [DOMAIN][crlf]X-YouTube: true[crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },

  // SPECIALIZED (50+)
  { name: "Netflix Browse", payload: `GET /browse HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Spotify Browse", payload: `GET /browse HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "TikTok Feed", payload: `GET /aweme/v1/feed/ HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Discord API", payload: `GET /api/v9/users/@me HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Reddit Hot", payload: `GET /hot.json HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Twitch Mobile", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Steam Actions", payload: `GET /actions/ajaxgetusernews HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "GitHub Trending", payload: `GET /trending HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "LinkedIn Feed", payload: `GET /feed/ HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Twitter Timeline", payload: `GET /i/api/1.1/statuses/home_timeline.json HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "PayPal Login", payload: `GET /sign-in HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Binance Trade", payload: `GET /trade HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Canva Design", payload: `GET /design HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Slack Workspace", payload: `GET /client HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Trello Board", payload: `GET /boards HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Notion Page", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Evernote Note", payload: `GET /home.action HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Duolingo Lesson", payload: `GET /learn HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Strava Run", payload: `GET /runs HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "MyFitness Track", payload: `GET /track HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Waze Navigation", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Foodpanda Order", payload: `GET /order HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Airbnb Search", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Booking Hotel", payload: `GET /hotels HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "TripAdvisor", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Weather Accu", payload: `GET /en/my/kuala-lumpur/weather HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "IMDB Search", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Goodreads Book", payload: `GET /book/show HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "SoundCloud Track", payload: `GET /track HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Vimeo Video", payload: `GET /video HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Dribbble Shot", payload: `GET /shots HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Behance Project", payload: `GET /projects HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Unsplash Photo", payload: `GET /photos HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Pexels Image", payload: `GET /v1/search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Pixabay Search", payload: `GET /api/ HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Freepik Vector", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Envato Elements", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Adobe Stock", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Shutterstock", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Getty Images", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "iStock Photo", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "Depositphotos", payload: `GET / HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` },
  { name: "Alamy Stock", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket:[DOMAIN][crlf][crlf]` },
  { name: "123RF Image", payload: `GET /search HTTP/1.1[crlf]Host: [DOMAIN][crlf][crlf]GET-RAY / HTTP/1.1[crlf]Host: [TUNNEL][crlf]Connection: Upgrade[crlf]User-Agent: [UA][crlf]Upgrade: websocket[crlf][crlf]` }
];
